/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import Entidades.FacturaVentacCab;
import Entidades.FacturaVentasDet;
import Entidades.Productos;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author parivera
 */
public class frmIngresarVentas extends javax.swing.JFrame {

    /**
     * Creates new form frmIngresarVentas
     */
    private boolean editar = false;
    ArrayList<Productos> Productos= null;
    double _subtotal;
    double _iva;
    double _total;
    
    public frmIngresarVentas() {
        initComponents();
        editar = false;
    }
    
    private Connection con;

    frmIngresarVentas(FacturaVentacCab f) {
        initComponents();
        tfCodigo.setText(f.getCodigoFactura());
        tfCliente.setText(f.getIdCliente());
        jcmbEstado.setSelectedItem(f.getEstado());
        tfFecha.setText(f.getFecha().toString());
        jlIva.setText(String.valueOf(f.getIva()));
        jlSubtotal.setText(String.valueOf(f.getSubtotal()));
        jlTotal.setText(String.valueOf(f.getTotal()));
        
        tfCodigo.setEditable(false);
        tfCliente.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bLimpiar = new javax.swing.JButton();
        lCodigo = new javax.swing.JLabel();
        lFecha = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        lNombre = new javax.swing.JLabel();
        tfFecha = new javax.swing.JTextField();
        lEstado = new javax.swing.JLabel();
        lCantidad1 = new javax.swing.JLabel();
        lCantidad = new javax.swing.JLabel();
        tfCliente = new javax.swing.JTextField();
        lCantidad2 = new javax.swing.JLabel();
        bIngresar = new javax.swing.JButton();
        jcmbEstado = new javax.swing.JComboBox<>();
        jSProductos = new javax.swing.JScrollPane();
        jResultados = new javax.swing.JTable();
        jbPreordenar = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jlSubtotal = new javax.swing.JLabel();
        jlIva = new javax.swing.JLabel();
        jlTotal = new javax.swing.JLabel();
        jbElimnarProd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bLimpiar.setText("Anular");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        lCodigo.setText("CODIGO");

        lFecha.setText("FECHA ");

        tfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoActionPerformed(evt);
            }
        });

        lNombre.setText("CLIENTE ID");

        lEstado.setText("ESTADO");

        lCantidad1.setText("TOTAL");

        lCantidad.setText("SUBTOTAL");

        lCantidad2.setText("VALOR IVA");

        bIngresar.setText("INGRESAR");
        bIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresarActionPerformed(evt);
            }
        });

        jcmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un estado", "Efectiva", "Anulada" }));

        jResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "CODIGO PRODUCTO", "CANTIDAD", "VALOR UNITARIO", "TOTAL"
            }
        ));
        jSProductos.setViewportView(jResultados);

        jbPreordenar.setText("PRE-ORDENAR");
        jbPreordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPreordenarActionPerformed(evt);
            }
        });

        jbActualizar.setText("ACTUALIZAR");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jlSubtotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlSubtotal.setText("$ -");

        jlIva.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlIva.setText("$ -");

        jlTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlTotal.setText("$ -");

        jbElimnarProd.setText("Eliminar");
        jbElimnarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbElimnarProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jbPreordenar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(bIngresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bLimpiar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                            .addComponent(lFecha)
                            .addComponent(lCodigo))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCliente)
                            .addComponent(tfFecha)
                            .addComponent(tfCodigo)
                            .addComponent(jcmbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lCantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lCantidad2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(lCantidad1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlIva, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbElimnarProd)
                        .addGap(250, 250, 250)
                        .addComponent(jbActualizar)))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCodigo)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lFecha)
                    .addComponent(tfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbPreordenar)
                .addGap(18, 18, 18)
                .addComponent(jSProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbElimnarProd)
                    .addComponent(jbActualizar))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSubtotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlIva))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bIngresar)
                    .addComponent(bLimpiar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void tfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoActionPerformed

    private void bIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresarActionPerformed
        if(ValidacionControles()){
            PreparedStatement st = null;
            try {
                LocalDate todayLocalDate = LocalDate.now( ZoneId.of( "America/Montreal" ) );

                con = Conexion.Conexion.conectar();
                if (editar) {
                    /*st = con.prepareStatement("UPDATE productos set nombre=?, marca = ?, fecha_caducidad = ?, cantidad=?, precio=?, iva=?  WHERE codigo = ?");
                    st.setString(1, p.getNombre());
                    st.setString(2, p.getMarca());
                    st.setDate(3, Date.valueOf(todayLocalDate));
                    st.setInt(4, p.getCantidad());
                    st.setString(5, p.getPrecio());
                    st.setString(6, p.getIva());
                    st.setInt(7, p.getCodigo());

                    st.executeUpdate();

                    System.out.println("Actualización de productos exitosa");*/
                
                }
                limpiarFormulario();

                dispose();
            } catch (SQLException ex) {
                Logger.getLogger(FrmIngresoProducto.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(FrmIngresoProducto.class.getName()).log(Level.SEVERE, null, ex);
            } finally{

                if (con!=null) {
                    try {
                        con.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(FrmIngresarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

                if (st!=null) {
                    try{
                        st.close();
                    }catch (SQLException ex) {
                        Logger.getLogger(FrmIngresarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_bIngresarActionPerformed

    private void jbPreordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPreordenarActionPerformed
        if (ValidacionControles()) {
            PreparedStatement st = null;
            LocalDate todayLocalDate = LocalDate.now( ZoneId.of( "America/Montreal" ) );
            try {
                FacturaVentacCab f = new FacturaVentacCab(jcmbEstado.getSelectedItem().toString(), tfCodigo.getText(), Date.valueOf(todayLocalDate),tfCliente.getText());
                con = Conexion.Conexion.conectar();
                                
                st = con.prepareStatement("INSERT INTO ventascabecera(idventas,codigo,idcliente,fecha,estado) VALUES(null,?,?,?,?) ");
                st.setString(1, f.getCodigoFactura());
                st.setString(2, f.getIdCliente());                    
                st.setDate(3, Date.valueOf(todayLocalDate));
                st.setString(4, f.getEstado());

                st.executeUpdate();

                System.out.println("Ingreso de preventa exitoso");

                JOptionPane.showMessageDialog(this,
                    "Ingrese este codigo de venta en la aplicación del telefono: " + f.getCodigoFactura(),
                    "Factura Venta",
                    JOptionPane.INFORMATION_MESSAGE);

            } catch (Exception e) {
                System.out.println("Problema en la base al pre-ordenar");
            }finally{

                if (con!=null) {
                    try {
                        con.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(FrmIngresarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

                if (st!=null) {
                    try{
                        st.close();
                    }catch (SQLException ex) {
                        Logger.getLogger(FrmIngresarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_jbPreordenarActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        PreparedStatement st = null;
        ResultSet rs=null;
        Productos= new ArrayList<>();
        try {
            con = Conexion.Conexion.conectar();
            ArrayList<FacturaVentasDet> resultado= new ArrayList<>();
            
            st = con.prepareStatement("select codigoproducto, cantidad from ventasdetalle where codigofactura = ?");
            st.setString(1, tfCodigo.getText());

            rs = st.executeQuery();
            
            while (rs.next()) {                
                resultado.add(new FacturaVentasDet(null,Integer.parseInt(rs.getString("cantidad")), rs.getString("codigoproducto")));
            }
            
            for (int i = 0; i < resultado.size(); i++) {
                st = null;
                rs = null;
                st = con.prepareStatement("select codigo,cantidad, precio, iva cantidad from productos where codigo = ?");
                st.setString(1, resultado.get(i).getCodigoProducto());  
                rs = st.executeQuery();
                while(rs.next()){
                    Productos.add(new Productos(Integer.parseInt(rs.getString("codigo")), Integer.parseInt(rs.getString("cantidad"))
                            , Double.parseDouble(rs.getString("precio")), Double.parseDouble(rs.getString("iva"))));
                }
            }
            
            _subtotal =0;
            _iva = 0;
            //recorre los lista de productos: asigna y calcula el volor total de cada prodcuto de la venta
            for (int i = 0; i < Productos.size(); i++) {
                for (int j = 0; j < resultado.size(); j++) {                    
                    if (String.valueOf(Productos.get(i).getCodigo()) == null ? resultado.get(j).getCodigoProducto() == null : 
                            String.valueOf(Productos.get(i).getCodigo()).equals(resultado.get(j).getCodigoProducto())) {
                        
                        resultado.get(j).setCostoUnitario(Productos.get(i).getPrecio());
                        
                        resultado.get(j).setTotal(Productos.get(i).getPrecio() * resultado.get(j).getCantidad() );
                        
                        _subtotal += resultado.get(j).getTotal();
                        
                        _iva += (resultado.get(j).getTotal() * Productos.get(i).getIva());
                    }                    
                }                
            }
            
            _total = _subtotal + _iva;

            DefaultTableModel dtm = (DefaultTableModel) jResultados.getModel();
            dtm.setRowCount(0);
            ArrayList<Object> fila;
            for (FacturaVentasDet p:resultado) {
                fila = new ArrayList<>();
                fila.add(p.getCodigoProducto());
                fila.add(p.getCantidad());
                fila.add(p.getCostoUnitario());
                fila.add(p.getTotal());
                dtm.addRow(fila.toArray());
            }
            
            jlIva.setText(String.valueOf(_iva));
            jlSubtotal.setText(String.valueOf(_subtotal));
            jlTotal.setText(String.valueOf(_total));
            
        } catch (Exception e) {
        }finally{

            if (con!=null) {
                try {
                    con.close();
                } catch (SQLException ex) {
                    Logger.getLogger(FrmIngresarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            if (st!=null) {
                try{
                    st.close();
                }catch (SQLException ex) {
                    Logger.getLogger(FrmIngresarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jbElimnarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbElimnarProdActionPerformed
        if (seleccionEdicionValida()) {
            
        }
    }//GEN-LAST:event_jbElimnarProdActionPerformed

    /**
     * 
     * @return
     */
    public boolean seleccionEdicionValida(){        
        if(!(jResultados.getSelectedRowCount() >=1)){
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar al menos un registro a editar o eliminar",
                    "Ventas",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }        
        return true;    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmIngresarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmIngresarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmIngresarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmIngresarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmIngresarVentas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIngresar;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JTable jResultados;
    private javax.swing.JScrollPane jSProductos;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbElimnarProd;
    private javax.swing.JButton jbPreordenar;
    private javax.swing.JComboBox<String> jcmbEstado;
    private javax.swing.JLabel jlIva;
    private javax.swing.JLabel jlSubtotal;
    private javax.swing.JLabel jlTotal;
    private javax.swing.JLabel lCantidad;
    private javax.swing.JLabel lCantidad1;
    private javax.swing.JLabel lCantidad2;
    private javax.swing.JLabel lCodigo;
    private javax.swing.JLabel lEstado;
    private javax.swing.JLabel lFecha;
    private javax.swing.JLabel lNombre;
    private javax.swing.JTextField tfCliente;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfFecha;
    // End of variables declaration//GEN-END:variables

    private void limpiarFormulario() {
        tfCliente.setText(null);
        tfCodigo.setText(null);
        tfFecha.setText(null);
        jcmbEstado.setSelectedIndex(0);
        jlIva.setText(null);
        jlSubtotal.setText(null);
        jlTotal.setText(null);        
        
        for (int i = ((DefaultTableModel)jResultados.getModel()).getRowCount(); i >= 0; i--) {
            ((DefaultTableModel)jResultados.getModel()).removeRow(i);
        }
    }

    private boolean ValidacionControles() {
        try {
            Integer.parseInt(tfCodigo.getText());            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "El código debe tener valores válidos",
                "Factura Venta",
                JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (jcmbEstado.getSelectedItem().toString().equalsIgnoreCase("seleccione un estado")) {
            JOptionPane.showMessageDialog(this,
                "Debe seleccionar un estado válido",
                "Factura Venta",
                JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return facturaValido(tfCodigo.getText());
    }
    
    private boolean facturaValido(String _codigo) {      
        
        ResultSet rs=null;                       
        PreparedStatement st=null;
        try
        {   
            con = Conexion.Conexion.conectar();
            st = con.prepareStatement("SELECT * FROM ventascabecera WHERE codigo = ?");            
            st.setString(1,_codigo);    
            rs = st.executeQuery(); 
            if(rs.next()){
                JOptionPane.showMessageDialog(this,
                    "Existe una con el mismo código",
                    "Facturacion",
                    JOptionPane.ERROR_MESSAGE);
                return false;
            }
            return true;
        }        
        catch(Exception e){
                JOptionPane.showMessageDialog(this,
                    "Error en la consulta de factura. (Validación) \n" + e,
                    "Facturacion ",
                    JOptionPane.ERROR_MESSAGE);          
            return false;
        } finally{
            if ( con!=null) {
                try {
                    con.close();
                } catch (SQLException ex) {
                    Logger.getLogger(FrmIngresarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (st!=null) {
                try{
                    st.close();
                }catch (SQLException ex) {
                    Logger.getLogger(FrmIngresarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            if (rs!= null) {
                try{
                    rs.close();
                }catch (SQLException ex) {
                    Logger.getLogger(FrmIngresarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
    }
}
