/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import Entidades.usuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     * @param u
     */
    public FrmPrincipal(usuarios u) {
        initComponents();
        if ("operador".equalsIgnoreCase(u.getRol())) {
            miIngresarUsuario.setVisible(false);
        }
    }

    FrmPrincipal() {
        //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mbPrincipal = new javax.swing.JMenuBar();
        mIncio = new javax.swing.JMenu();
        miCerrarSesion = new javax.swing.JMenuItem();
        miSalir = new javax.swing.JMenuItem();
        mMantenimiento = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        miProductos = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jmFacturas = new javax.swing.JMenu();
        jmVentas = new javax.swing.JMenuItem();
        jmReportes = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mIntegrantes = new javax.swing.JMenu();
        miIntegrantes = new javax.swing.JMenuItem();
        mConfiguracion = new javax.swing.JMenu();
        miIngresarUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mIncio.setText("INICIO");

        miCerrarSesion.setText("Cerrar sesion");
        miCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCerrarSesionActionPerformed(evt);
            }
        });
        mIncio.add(miCerrarSesion);

        miSalir.setText("Salir");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        mIncio.add(miSalir);

        mbPrincipal.add(mIncio);

        mMantenimiento.setText("MANTENIMIENTO");

        jMenuItem4.setText("Clientes");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mMantenimiento.add(jMenuItem4);

        miProductos.setText("Productos");
        miProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProductosActionPerformed(evt);
            }
        });
        mMantenimiento.add(miProductos);

        jMenuItem5.setText("Proveedores");
        mMantenimiento.add(jMenuItem5);

        jmFacturas.setText("Facturas");
        jmFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFacturasActionPerformed(evt);
            }
        });

        jmVentas.setText("Ventas");
        jmVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmVentasActionPerformed(evt);
            }
        });
        jmFacturas.add(jmVentas);

        mMantenimiento.add(jmFacturas);

        mbPrincipal.add(mMantenimiento);

        jmReportes.setText("REPORTES");

        jMenuItem2.setText("Compras");
        jmReportes.add(jMenuItem2);

        jMenuItem3.setText("Ventas");
        jmReportes.add(jMenuItem3);

        jMenuItem1.setText("Facturacion");
        jmReportes.add(jMenuItem1);

        mbPrincipal.add(jmReportes);

        mIntegrantes.setText("INFORMACIÓN");

        miIntegrantes.setText("Integrantes");
        miIntegrantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miIntegrantesActionPerformed(evt);
            }
        });
        mIntegrantes.add(miIntegrantes);

        mbPrincipal.add(mIntegrantes);

        mConfiguracion.setText("CONFIGURACIÓN");

        miIngresarUsuario.setText("Usuarios");
        miIngresarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miIngresarUsuarioActionPerformed(evt);
            }
        });
        mConfiguracion.add(miIngresarUsuario);

        mbPrincipal.add(mConfiguracion);

        setJMenuBar(mbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_miSalirActionPerformed

    private void miProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProductosActionPerformed
        FrmMantenimientoProducto frm = new FrmMantenimientoProducto();
        frm.setVisible(true);
    }//GEN-LAST:event_miProductosActionPerformed

    private void miIntegrantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miIntegrantesActionPerformed
        frmIntegrantes frm = new frmIntegrantes();
        frm.setVisible(true);
    }//GEN-LAST:event_miIntegrantesActionPerformed

    private void miCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCerrarSesionActionPerformed
        int resp = JOptionPane.showConfirmDialog(null,"desea cerrar Sesion?");
        if (resp == JOptionPane.OK_OPTION) {
            frmlogin frm = new frmlogin();
            frm.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_miCerrarSesionActionPerformed

    private void miIngresarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miIngresarUsuarioActionPerformed
        FrmMantenimientoUsuarios frm = new FrmMantenimientoUsuarios();
        frm.setVisible(true);
    }//GEN-LAST:event_miIngresarUsuarioActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        frmlogin frm = new frmlogin();
        frm.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void jmFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFacturasActionPerformed

    }//GEN-LAST:event_jmFacturasActionPerformed

    private void jmVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmVentasActionPerformed
        frmMantenimientoFactura frm = new frmMantenimientoFactura();
        frm.setVisible(true);
    }//GEN-LAST:event_jmVentasActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        FrmMantenimientoCliente frm = new FrmMantenimientoCliente();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu jmFacturas;
    private javax.swing.JMenu jmReportes;
    private javax.swing.JMenuItem jmVentas;
    private javax.swing.JMenu mConfiguracion;
    private javax.swing.JMenu mIncio;
    private javax.swing.JMenu mIntegrantes;
    private javax.swing.JMenu mMantenimiento;
    private javax.swing.JMenuBar mbPrincipal;
    private javax.swing.JMenuItem miCerrarSesion;
    private javax.swing.JMenuItem miIngresarUsuario;
    private javax.swing.JMenuItem miIntegrantes;
    private javax.swing.JMenuItem miProductos;
    private javax.swing.JMenuItem miSalir;
    // End of variables declaration//GEN-END:variables
}
